language: node_js
node_js:
  - 12
  
services:
  - docker
  
script:
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  
# Tag
  - docker tag udagram-api-feed unihornkccrlq/udagram-api-feed:v0
  - docker tag udagram-api-user unihornkccrlq/udagram-api-user:v0
  - docker tag udagram-frontend unihornkccrlq/udagram-frontend:v0
  - docker tag reverseproxy unihornkccrlq/reverseproxy:v0
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push unihornkccrlq/udagram-api-feed:v0
  - docker push unihornkccrlq/udagram-api-user:v0
  - docker push unihornkccrlq/udagram-frontend:v0
  - docker push unihornkccrlq/reverseproxy:v0
