apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler
  labels:
    app: autoscaler-display
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-api-user
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
