apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-user
  labels:
    app: backend-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api-user
  template:
    metadata:
      labels:
        app: backend-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: unihornkccrlq/udagram-api-user:v0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: udagram-configmap
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
        ports:
        - containerPort: 80
      restartPolicy: Always
