apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-api
  name: frontend-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-api
  type: LoadBalancer
