apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-api
  labels:
    app: frontend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-api
  template:
    metadata:
      labels:
        app: frontend-api
    spec:
      containers:
      - name: udagram-frontend
        image: unihornkccrlq/udagram-frontend:v2
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: udagram-configmap
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
        ports:
        - containerPort: 80
      restartPolicy: Always
