apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: udagram-api-feed
        image: unihornkccrlq/reverseproxy:v0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: udagram-configmap
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
        ports:
        - containerPort: 80
      restartPolicy: Always
